name: Hello World
on: 
  pull_request:
    branches:
      main
jobs:
  Hello-World-Job:
    runs-on: codebuild-ncrs-int-deployment-${{ github.run_id }}-${{ github.run_attempt }}-arm-3.0-small
    steps:
      - run: echo "Hello World!"
